using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ILCompiler
{
    public class MemoryMap
    {
        public MemoryAddress[] cells;
        public MemoryMap()
        {
            cells = new MemoryAddress[]
            {
                new MemoryAddress("MW0",     0x00),
                new MemoryAddress("MW1",     0x01),
                new MemoryAddress("MW2",     0x02),
                new MemoryAddress("MW3",     0x03),
                new MemoryAddress("MW4",     0x04),
                new MemoryAddress("MW5",     0x05),
                new MemoryAddress("MW6",     0x06),
                new MemoryAddress("MW7",     0x07),
                new MemoryAddress("MW8",     0x08),
                new MemoryAddress("MW9",     0x09),
                new MemoryAddress("MW10",    0x0A),
                new MemoryAddress("MW11",    0x0B),
                new MemoryAddress("MW12",    0x0C),
                new MemoryAddress("MW13",    0x0D),
                new MemoryAddress("MW14",    0x0E),
                new MemoryAddress("MW15",    0x0F),
                new MemoryAddress("MW16",    0x10),
                new MemoryAddress("MW17",    0x11),
                new MemoryAddress("MW18",    0x12),
                new MemoryAddress("MW19",    0x13),
                new MemoryAddress("MW20",    0x14),
                new MemoryAddress("MW21",    0x15),
                new MemoryAddress("MW22",    0x16),
                new MemoryAddress("MW23",    0x17),
                new MemoryAddress("MW24",    0x18),
                new MemoryAddress("MW25",    0x19),
                new MemoryAddress("MW26",    0x1A),
                new MemoryAddress("MW27",    0x1B),
                new MemoryAddress("MW28",    0x1C),
                new MemoryAddress("MW29",    0x1D),
                new MemoryAddress("MW30",    0x1E),
                new MemoryAddress("MW31",    0x1F),
                new MemoryAddress("MW32",    0x20),
                new MemoryAddress("MW33",    0x21),
                new MemoryAddress("MW34",    0x22),
                new MemoryAddress("MW35",    0x23),
                new MemoryAddress("MW36",    0x24),
                new MemoryAddress("MW37",    0x25),
                new MemoryAddress("MW38",    0x26),
                new MemoryAddress("MW39",    0x27),
                new MemoryAddress("MW40",    0x28),
                new MemoryAddress("MW41",    0x29),
                new MemoryAddress("MW42",    0x2A),
                new MemoryAddress("MW43",    0x2B),
                new MemoryAddress("MW44",    0x2C),
                new MemoryAddress("MW45",    0x2D),
                new MemoryAddress("MW46",    0x2E),
                new MemoryAddress("MW47",    0x2F),
                new MemoryAddress("MW48",    0x30),
                new MemoryAddress("MW49",    0x31),
                new MemoryAddress("MW50",    0x32),
                new MemoryAddress("MW51",    0x33),
                new MemoryAddress("MW52",    0x34),
                new MemoryAddress("MW53",    0x35),
                new MemoryAddress("MW54",    0x36),
                new MemoryAddress("MW55",    0x37),
                new MemoryAddress("MW56",    0x38),
                new MemoryAddress("MW57",    0x39),
                new MemoryAddress("MW58",    0x3A),
                new MemoryAddress("MW59",    0x3B),
                new MemoryAddress("MW60",    0x3C),
                new MemoryAddress("MW61",    0x3D),
                new MemoryAddress("MW62",    0x3E),
                new MemoryAddress("MW63",    0x3F),

                new MemoryAddress("MW0.0",   0x80),
                new MemoryAddress("MW0.1",   0x81),
                new MemoryAddress("MW0.2",   0x82),
                new MemoryAddress("MW0.3",   0x83),
                new MemoryAddress("MW0.4",   0x84),
                new MemoryAddress("MW0.5",   0x85),
                new MemoryAddress("MW0.6",   0x86),
                new MemoryAddress("MW0.7",   0x87),
                new MemoryAddress("MW0.8",   0x88),
                new MemoryAddress("MW0.9",   0x89),
                new MemoryAddress("MW0.10",  0x8A),
                new MemoryAddress("MW0.11",  0x8B),
                new MemoryAddress("MW0.12",  0x8C),
                new MemoryAddress("MW0.13",  0x8D),
                new MemoryAddress("MW0.14",  0x8E),
                new MemoryAddress("MW0.15",  0x8F),
                new MemoryAddress("MW0.16",  0x90),
                new MemoryAddress("MW0.17",  0x91),
                new MemoryAddress("MW0.18",  0x92),
                new MemoryAddress("MW0.19",  0x93),
                new MemoryAddress("MW0.20",  0x94),
                new MemoryAddress("MW0.21",  0x95),
                new MemoryAddress("MW0.22",  0x96),
                new MemoryAddress("MW0.23",  0x97),
                new MemoryAddress("MW0.24",  0x98),
                new MemoryAddress("MW0.25",  0x99),
                new MemoryAddress("MW0.26",  0x9A),
                new MemoryAddress("MW0.27",  0x9B),
                new MemoryAddress("MW0.28",  0x9C),
                new MemoryAddress("MW0.29",  0x9D),
                new MemoryAddress("MW0.30",  0x9E),
                new MemoryAddress("MW0.31",  0x9F),
                new MemoryAddress("MW1.0",   0xA0),
                new MemoryAddress("MW1.1",   0xA1),
                new MemoryAddress("MW1.2",   0xA2),
                new MemoryAddress("MW1.3",   0xA3),
                new MemoryAddress("MW1.4",   0xA4),
                new MemoryAddress("MW1.5",   0xA5),
                new MemoryAddress("MW1.6",   0xA6),
                new MemoryAddress("MW1.7",   0xA7),
                new MemoryAddress("MW1.8",   0xA8),
                new MemoryAddress("MW1.9",   0xA9),
                new MemoryAddress("MW1.10",  0xAA),
                new MemoryAddress("MW1.11",  0xAB),
                new MemoryAddress("MW1.12",  0xAC),
                new MemoryAddress("MW1.13",  0xAD),
                new MemoryAddress("MW1.14",  0xAE),
                new MemoryAddress("MW1.15",  0xAF),
                new MemoryAddress("MW1.16",  0xB0),
                new MemoryAddress("MW1.17",  0xB1),
                new MemoryAddress("MW1.18",  0xB2),
                new MemoryAddress("MW1.19",  0xB3),
                new MemoryAddress("MW1.20",  0xB4),
                new MemoryAddress("MW1.21",  0xB5),
                new MemoryAddress("MW1.22",  0xB6),
                new MemoryAddress("MW1.23",  0xB7),
                new MemoryAddress("MW1.24",  0xB8),
                new MemoryAddress("MW1.25",  0xB9),
                new MemoryAddress("MW1.26",  0xBA),
                new MemoryAddress("MW1.27",  0xBB),
                new MemoryAddress("MW1.28",  0xBC),
                new MemoryAddress("MW1.29",  0xBD),
                new MemoryAddress("MW1.30",  0xBE),
                new MemoryAddress("MW1.31",  0xBF),

                new MemoryAddress("C0",      0x40),
                new MemoryAddress("C1",      0x41),
                new MemoryAddress("C2",      0x42),
                new MemoryAddress("C3",      0x43),
                new MemoryAddress("C4",      0x44),
                new MemoryAddress("C5",      0x45),
                new MemoryAddress("C6",      0x46),
                new MemoryAddress("C7",      0x47),
                new MemoryAddress("C8",      0x48),
                new MemoryAddress("C9",      0x49),
                new MemoryAddress("C10",     0x4A),
                new MemoryAddress("C11",     0x4B),
                new MemoryAddress("C12",     0x4C),
                new MemoryAddress("C13",     0x4D),
                new MemoryAddress("C14",     0x4E),
                new MemoryAddress("C15",     0x4F),

                new MemoryAddress("T0",      0x50),
                new MemoryAddress("T1",      0x51),
                new MemoryAddress("T2",      0x52),
                new MemoryAddress("T3",      0x53),
                new MemoryAddress("T4",      0x54),
                new MemoryAddress("T5",      0x55),
                new MemoryAddress("T6",      0x56),
                new MemoryAddress("T7",      0x57),
                new MemoryAddress("T8",      0x58),
                new MemoryAddress("T9",      0x59),
                new MemoryAddress("T10",     0x5A),
                new MemoryAddress("T11",     0x5B),
                new MemoryAddress("T12",     0x5C),
                new MemoryAddress("T13",     0x5D),
                new MemoryAddress("T14",     0x5E),
                new MemoryAddress("T15",     0x5F),


                new MemoryAddress("DIW0",    0x60),
                new MemoryAddress("DIW1",    0x61),
                new MemoryAddress("DIW2",    0x62),
                new MemoryAddress("DIW3",    0x63),

                new MemoryAddress("DIW0.0",  0xC0),
                new MemoryAddress("DIW0.1",  0xC1),
                new MemoryAddress("DIW0.2",  0xC2),
                new MemoryAddress("DIW0.3",  0xC3),
                new MemoryAddress("DIW0.4",  0xC4),
                new MemoryAddress("DIW0.5",  0xC5),
                new MemoryAddress("DIW0.6",  0xC6),
                new MemoryAddress("DIW0.7",  0xC7),
                new MemoryAddress("DIW0.8",  0xC8),
                new MemoryAddress("DIW0.9",  0xC9),
                new MemoryAddress("DIW0.10", 0xCA),
                new MemoryAddress("DIW0.11", 0xCB),
                new MemoryAddress("DIW0.12", 0xCC),
                new MemoryAddress("DIW0.13", 0xCD),
                new MemoryAddress("DIW0.14", 0xCE),
                new MemoryAddress("DIW0.15", 0xCF),
                new MemoryAddress("DIW0.16", 0xD0),
                new MemoryAddress("DIW0.17", 0xD1),
                new MemoryAddress("DIW0.18", 0xD2),
                new MemoryAddress("DIW0.19", 0xD3),
                new MemoryAddress("DIW0.20", 0xD4),
                new MemoryAddress("DIW0.21", 0xD5),
                new MemoryAddress("DIW0.22", 0xD6),
                new MemoryAddress("DIW0.23", 0xD7),
                new MemoryAddress("DIW0.24", 0xD8),
                new MemoryAddress("DIW0.25", 0xD9),
                new MemoryAddress("DIW0.26", 0xDA),
                new MemoryAddress("DIW0.27", 0xDB),
                new MemoryAddress("DIW0.28", 0xDC),
                new MemoryAddress("DIW0.29", 0xDD),
                new MemoryAddress("DIW0.30", 0xDE),
                new MemoryAddress("DIW0.31", 0xDF),

                new MemoryAddress("DQW0",    0x64),
                new MemoryAddress("DQW1",    0x65),
                new MemoryAddress("DQW2",    0x66),
                new MemoryAddress("DQW3",    0x67),

                new MemoryAddress("DQW0.0",  0xE0),
                new MemoryAddress("DQW0.1",  0xE1),
                new MemoryAddress("DQW0.2",  0xE2),
                new MemoryAddress("DQW0.3",  0xE3),
                new MemoryAddress("DQW0.4",  0xE4),
                new MemoryAddress("DQW0.5",  0xE5),
                new MemoryAddress("DQW0.6",  0xE6),
                new MemoryAddress("DQW0.7",  0xE7),
                new MemoryAddress("DQW0.8",  0xE8),
                new MemoryAddress("DQW0.9",  0xE9),
                new MemoryAddress("DQW0.10", 0xEA),
                new MemoryAddress("DQW0.11", 0xEB),
                new MemoryAddress("DQW0.12", 0xEC),
                new MemoryAddress("DQW0.13", 0xED),
                new MemoryAddress("DQW0.14", 0xEE),
                new MemoryAddress("DQW0.15", 0xEF),
                new MemoryAddress("DQW0.16", 0xF0),
                new MemoryAddress("DQW0.17", 0xF1),
                new MemoryAddress("DQW0.18", 0xF2),
                new MemoryAddress("DQW0.19", 0xF3),
                new MemoryAddress("DQW0.20", 0xF4),
                new MemoryAddress("DQW0.21", 0xF5),
                new MemoryAddress("DQW0.22", 0xF6),
                new MemoryAddress("DQW0.23", 0xF7),
                new MemoryAddress("DQW0.24", 0xF8),
                new MemoryAddress("DQW0.25", 0xF9),
                new MemoryAddress("DQW0.26", 0xFA),
                new MemoryAddress("DQW0.27", 0xFB),
                new MemoryAddress("DQW0.28", 0xFC),
                new MemoryAddress("DQW0.29", 0xFD),
                new MemoryAddress("DQW0.30", 0xFE),
                new MemoryAddress("DQW0.31", 0xFF),

                new MemoryAddress("AI0",     0x68),
                new MemoryAddress("AI1",     0x69),
                new MemoryAddress("AI2",     0x6A),
                new MemoryAddress("AI3",     0x6B),
                new MemoryAddress("AI4",     0x6C),
                new MemoryAddress("AI5",     0x6D),
                new MemoryAddress("AI6",     0x6E),
                new MemoryAddress("AI7",     0x6F),
                new MemoryAddress("AI8",     0x70),
                new MemoryAddress("AI9",     0x71),
                new MemoryAddress("AI10",    0x72),
                new MemoryAddress("AI11",    0x73),
                new MemoryAddress("AI12",    0x74),
                new MemoryAddress("AI13",    0x75),
                new MemoryAddress("AI14",    0x76),
                new MemoryAddress("AI15",    0x77),

                new MemoryAddress("AQ0",     0x78),
                new MemoryAddress("AQ1",     0x79),
                new MemoryAddress("AQ2",     0x7A),
                new MemoryAddress("AQ3",     0x7B),
                new MemoryAddress("AQ4",     0x7C),
                new MemoryAddress("AQ5",     0x7D),
                new MemoryAddress("AQ6",     0x7E),
                new MemoryAddress("AQ7",     0x7F)
            };
        }

        public int getAddress(string mem)
        {
            for(int i = 0; i < cells.Length; i++)
            {
                if(string.Equals(cells[i].name, mem))
                {
                    return cells[i].address;
                }
            }
            return 0;
        }
    }
}